plugins {
    id 'xyz.wagyourtail.unimined' // version '4.2.0'
}

// this is just here so we can test the outputs easier and clean between tests
unimined.useGlobalCache = false

unimined.minecraft {
	minecraftData.metadataURL = uri("https://meta.omniarchive.uk/versions/v1/in-20091223-1459.json")

    version("in-20091223-1459")
    side("client")

    mappings {
        ornitheGenVersion = 2
        calamus()
        feather(1)
    }
}
