[versions]
# Kotlin 2.2.0 is only supported by Gradle 9+. Gradle 9 removes support for Java 8.
kotlin = "2.1.20"
dokka = "2.0.0"

jb-annotations = "26.0.2-1"

guava = "33.4.8-jre"
gson = "2.13.1"

asm = "9.8"

tiny-remapper = "0.11.1"
unimined-mapping-library = "1.2.2"

binarypatcher = "1.1.1"
neo_binarypatcher = "4.0.7"
jbsdiff = "1.0"

commons-io = "2.20.0"
commons-compress = "1.28.0"

classtweaker = "0.2"

# JGit 5.x is the last version that supports Java 8.
jgit = "5.13.3.202401111512-r"

keyring = "1.0.2"
minecraftauth = "4.1.2"

junit = "5.12.0"

[libraries]

jb-annotations = { module = "org.jetbrains:annotations", version.ref = "jb-annotations" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

asm = { module = "org.ow2.asm:asm", version.ref = "asm"}
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm"}
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm"}
asm-analysis = { module = "org.ow2.asm:asm-analysis", version.ref = "asm"}
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm"}

tiny-remapper = { module = "net.fabricmc:tiny-remapper", version.ref = "tiny-remapper" }
unimined-mapping-library-jvm = { module = "xyz.wagyourtail.unimined.mapping:unimined-mapping-library-jvm", version.ref = "unimined-mapping-library" }

binarypatcher = { module = "net.minecraftforge:binarypatcher", version.ref = "binarypatcher" }
neo_binarypatcher = { module = "net.neoforged.installertools:binarypatcher", version.ref = "neo_binarypatcher" }
jbsdiff = { module = "io.sigpipe:jbsdiff", version.ref = "jbsdiff" }

classtweaker = { module = "net.fabricmc:class-tweaker", version.ref = "classtweaker" }

commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }

jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }

java-keyring = { module = "com.github.javakeyring:java-keyring", version.ref = "keyring" }
minecraftauth = { module = "net.raphimc:MinecraftAuth", version.ref = "minecraftauth" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[bundles]
asm-all = ["asm", "asm-commons", "asm-tree", "asm-analysis", "asm-util"]

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
