name: Run Tests
on: [push, pull_request]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  JDK_VERSION: 17

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        gradle: [
          "8.7",
          "8.10.2",
          "wrapper",
        ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /*
            !testing/
            !Writerside/

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.JDK_VERSION }}

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ matrix.gradle }}
          cache-read-only: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/heads/lts') }}

      - run: ./gradlew build check -x test --stacktrace --warning-mode fail

  # This job is used to feed the test matrix of next job to allow the tests to run in parallel
  prepare_test_matrix:
    # Lets wait to ensure it builds before going running tests
    needs: build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.JDK_VERSION }}

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-read-only: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/heads/lts') }}

      - run: ./gradlew writeActionsTestMatrix --stacktrace

      - id: set-matrix
        run: echo "matrix=$(cat build/test_matrix.json)" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  run_tests:
    needs: prepare_test_matrix

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows, macos ]
        test: ${{ fromJson(needs.prepare_test_matrix.outputs.matrix) }}

    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ matrix.os == 'macos' }}
    name: "${{ matrix.test.name }} (${{ matrix.os }})"
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.JDK_VERSION }}

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-read-only: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/heads/lts') }}

      - run: ./gradlew test --tests ${{ matrix.test.path }} --stacktrace
        id: test
        env:
          TEST_WARNING_MODE: fail

      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: "${{ matrix.test.name }} (${{ matrix.os }}) Results"
          path: "**/build/reports/"

      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: "${{ matrix.test.name }} (${{ matrix.os }}) Heap Dump"
          path: "*.hprof"